name: Angular 13 CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@master
      
    - name: Install angular cli
      run: npm install -g @angular/cli

    - name: Install Node.js
      uses: actions/setup-node@master
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build Angular application
      run: ng build
